version: '3.8'

services:
  mongo:
    image: emmryilmaz/dacka-server:mongo
    container_name: mongo_test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test_user
      - MONGO_INITDB_ROOT_PASSWORD=test_password
      - MONGO_INITDB_DATABASE=test_db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_test
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'

  redis:
    image: redis:6.2-alpine
    container_name: redis_test
    ports:
      - '6379:6379'

  fastapi_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: fastapi_test
    environment:
      - DATABASE_URL=mongodb://test_user:test_password@mongo_test:27017/test_db
      - MONGO_INITDB_DATABASE=test_db
      - JWT_PUBLIC_KEY=mock_public_key
      - JWT_PRIVATE_KEY=mock_private_key
      - REFRESH_TOKEN_EXPIRES_IN=60
      - ACCESS_TOKEN_EXPIRES_IN=15
      - ALGORITHM=RS256
      - CLIENT_ORIGIN=http://localhost:3000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq_test:5672/
      - FIREBASE_CREDENTIALS_PATH=/app/tests/mock_firebase_credentials.json
      - CELERY_RESULT_BACKEND=redis://redis_test:6379/0
      - REDIS_URL=redis://redis_test:6379
    volumes:
      - .:/app
    depends_on:
      - mongo
      - rabbitmq
      - redis
    command: pytest app-fastapi/tests

volumes:
  mongo_data:
  rabbitmq_data:

networks:
  default:
    driver: bridge